/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTodoRouteImport } from './routes/_authenticated/todo'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSocialRouteImport } from './routes/_authenticated/social'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQuestionnaireRouteImport } from './routes/_authenticated/questionnaire'
import { Route as AuthenticatedProjectAllocationRouteImport } from './routes/_authenticated/project-allocation'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPendingWorkRouteImport } from './routes/_authenticated/pending-work'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLmsIntegrationRouteImport } from './routes/_authenticated/lms-integration'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedInteractionRouteImport } from './routes/_authenticated/interaction'
import { Route as AuthenticatedFeedbackSuggestionsRouteImport } from './routes/_authenticated/feedback-suggestions'
import { Route as AuthenticatedDiaryRouteImport } from './routes/_authenticated/diary'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'
import { Route as AuthenticatedUIdRouteImport } from './routes/_authenticated/u/$id'
import { Route as AuthenticatedSuperAdminTodoRouteImport } from './routes/_authenticated/super-admin/todo'
import { Route as AuthenticatedSuperAdminSettingsRouteImport } from './routes/_authenticated/super-admin/settings'
import { Route as AuthenticatedSuperAdminQuestionnairesRouteImport } from './routes/_authenticated/super-admin/questionnaires'
import { Route as AuthenticatedSuperAdminProblemStatementsRouteImport } from './routes/_authenticated/super-admin/problem-statements'
import { Route as AuthenticatedSuperAdminPendingWorkRouteImport } from './routes/_authenticated/super-admin/pending-work'
import { Route as AuthenticatedSuperAdminLmsRouteImport } from './routes/_authenticated/super-admin/lms'
import { Route as AuthenticatedSuperAdminLeaderboardRouteImport } from './routes/_authenticated/super-admin/leaderboard'
import { Route as AuthenticatedSuperAdminDashboardRouteImport } from './routes/_authenticated/super-admin/dashboard'
import { Route as AuthenticatedSuperAdminDailyDiaryRouteImport } from './routes/_authenticated/super-admin/daily-diary'
import { Route as AuthenticatedSuperAdminAnnouncementsRouteImport } from './routes/_authenticated/super-admin/announcements'
import { Route as AuthenticatedSuperAdminAiAnalysisRouteImport } from './routes/_authenticated/super-admin/ai-analysis'
import { Route as AuthenticatedSuperAdminAdminManagementRouteImport } from './routes/_authenticated/super-admin/admin-management'
import { Route as AuthenticatedSuperAdminActivitiesRouteImport } from './routes/_authenticated/super-admin/activities'
import { Route as AuthenticatedStudentAttendanceRouteImport } from './routes/_authenticated/student.attendance'
import { Route as AuthenticatedAdminTodoRouteImport } from './routes/_authenticated/admin/todo'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminQuestionnairesRouteImport } from './routes/_authenticated/admin/questionnaires'
import { Route as AuthenticatedAdminPendingWorkRouteImport } from './routes/_authenticated/admin/pending-work'
import { Route as AuthenticatedAdminLmsRouteImport } from './routes/_authenticated/admin/lms'
import { Route as AuthenticatedAdminLeaderboardRouteImport } from './routes/_authenticated/admin/leaderboard'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminDailyDiaryRouteImport } from './routes/_authenticated/admin/daily-diary'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin/announcements'
import { Route as AuthenticatedAdminAiAnalysisRouteImport } from './routes/_authenticated/admin/ai-analysis'
import { Route as AuthenticatedAdminActivitiesRouteImport } from './routes/_authenticated/admin/activities'
import { Route as AuthenticatedSuperAdminOperationsInteractionsRouteImport } from './routes/_authenticated/super-admin/operations.interactions'
import { Route as AuthenticatedSuperAdminOperationsAttendanceRouteImport } from './routes/_authenticated/super-admin/operations.attendance'
import { Route as AuthenticatedSuperAdminInternsOnboardingRouteImport } from './routes/_authenticated/super-admin/interns.onboarding'
import { Route as AuthenticatedSuperAdminInternsActiveRouteImport } from './routes/_authenticated/super-admin/interns.active'
import { Route as AuthenticatedAdminOperationsInteractionsRouteImport } from './routes/_authenticated/admin/operations.interactions'
import { Route as AuthenticatedAdminOperationsAttendanceRouteImport } from './routes/_authenticated/admin/operations.attendance'
import { Route as AuthenticatedAdminInternsOnboardingRouteImport } from './routes/_authenticated/admin/interns.onboarding'
import { Route as AuthenticatedAdminInternsActiveRouteImport } from './routes/_authenticated/admin/interns.active'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTodoRoute = AuthenticatedTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocialRoute = AuthenticatedSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestionnaireRoute =
  AuthenticatedQuestionnaireRouteImport.update({
    id: '/questionnaire',
    path: '/questionnaire',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectAllocationRoute =
  AuthenticatedProjectAllocationRouteImport.update({
    id: '/project-allocation',
    path: '/project-allocation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendingWorkRoute =
  AuthenticatedPendingWorkRouteImport.update({
    id: '/pending-work',
    path: '/pending-work',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLmsIntegrationRoute =
  AuthenticatedLmsIntegrationRouteImport.update({
    id: '/lms-integration',
    path: '/lms-integration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInteractionRoute =
  AuthenticatedInteractionRouteImport.update({
    id: '/interaction',
    path: '/interaction',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedbackSuggestionsRoute =
  AuthenticatedFeedbackSuggestionsRouteImport.update({
    id: '/feedback-suggestions',
    path: '/feedback-suggestions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiaryRoute = AuthenticatedDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUIdRoute = AuthenticatedUIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperAdminTodoRoute =
  AuthenticatedSuperAdminTodoRouteImport.update({
    id: '/super-admin/todo',
    path: '/super-admin/todo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminSettingsRoute =
  AuthenticatedSuperAdminSettingsRouteImport.update({
    id: '/super-admin/settings',
    path: '/super-admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminQuestionnairesRoute =
  AuthenticatedSuperAdminQuestionnairesRouteImport.update({
    id: '/super-admin/questionnaires',
    path: '/super-admin/questionnaires',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminProblemStatementsRoute =
  AuthenticatedSuperAdminProblemStatementsRouteImport.update({
    id: '/super-admin/problem-statements',
    path: '/super-admin/problem-statements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminPendingWorkRoute =
  AuthenticatedSuperAdminPendingWorkRouteImport.update({
    id: '/super-admin/pending-work',
    path: '/super-admin/pending-work',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminLmsRoute =
  AuthenticatedSuperAdminLmsRouteImport.update({
    id: '/super-admin/lms',
    path: '/super-admin/lms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminLeaderboardRoute =
  AuthenticatedSuperAdminLeaderboardRouteImport.update({
    id: '/super-admin/leaderboard',
    path: '/super-admin/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminDashboardRoute =
  AuthenticatedSuperAdminDashboardRouteImport.update({
    id: '/super-admin/dashboard',
    path: '/super-admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminDailyDiaryRoute =
  AuthenticatedSuperAdminDailyDiaryRouteImport.update({
    id: '/super-admin/daily-diary',
    path: '/super-admin/daily-diary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminAnnouncementsRoute =
  AuthenticatedSuperAdminAnnouncementsRouteImport.update({
    id: '/super-admin/announcements',
    path: '/super-admin/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminAiAnalysisRoute =
  AuthenticatedSuperAdminAiAnalysisRouteImport.update({
    id: '/super-admin/ai-analysis',
    path: '/super-admin/ai-analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminAdminManagementRoute =
  AuthenticatedSuperAdminAdminManagementRouteImport.update({
    id: '/super-admin/admin-management',
    path: '/super-admin/admin-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminActivitiesRoute =
  AuthenticatedSuperAdminActivitiesRouteImport.update({
    id: '/super-admin/activities',
    path: '/super-admin/activities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentAttendanceRoute =
  AuthenticatedStudentAttendanceRouteImport.update({
    id: '/student/attendance',
    path: '/student/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTodoRoute = AuthenticatedAdminTodoRouteImport.update({
  id: '/admin/todo',
  path: '/admin/todo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQuestionnairesRoute =
  AuthenticatedAdminQuestionnairesRouteImport.update({
    id: '/admin/questionnaires',
    path: '/admin/questionnaires',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPendingWorkRoute =
  AuthenticatedAdminPendingWorkRouteImport.update({
    id: '/admin/pending-work',
    path: '/admin/pending-work',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLmsRoute = AuthenticatedAdminLmsRouteImport.update({
  id: '/admin/lms',
  path: '/admin/lms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminLeaderboardRoute =
  AuthenticatedAdminLeaderboardRouteImport.update({
    id: '/admin/leaderboard',
    path: '/admin/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDailyDiaryRoute =
  AuthenticatedAdminDailyDiaryRouteImport.update({
    id: '/admin/daily-diary',
    path: '/admin/daily-diary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/admin/announcements',
    path: '/admin/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAiAnalysisRoute =
  AuthenticatedAdminAiAnalysisRouteImport.update({
    id: '/admin/ai-analysis',
    path: '/admin/ai-analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminActivitiesRoute =
  AuthenticatedAdminActivitiesRouteImport.update({
    id: '/admin/activities',
    path: '/admin/activities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminOperationsInteractionsRoute =
  AuthenticatedSuperAdminOperationsInteractionsRouteImport.update({
    id: '/super-admin/operations/interactions',
    path: '/super-admin/operations/interactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminOperationsAttendanceRoute =
  AuthenticatedSuperAdminOperationsAttendanceRouteImport.update({
    id: '/super-admin/operations/attendance',
    path: '/super-admin/operations/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminInternsOnboardingRoute =
  AuthenticatedSuperAdminInternsOnboardingRouteImport.update({
    id: '/super-admin/interns/onboarding',
    path: '/super-admin/interns/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminInternsActiveRoute =
  AuthenticatedSuperAdminInternsActiveRouteImport.update({
    id: '/super-admin/interns/active',
    path: '/super-admin/interns/active',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOperationsInteractionsRoute =
  AuthenticatedAdminOperationsInteractionsRouteImport.update({
    id: '/admin/operations/interactions',
    path: '/admin/operations/interactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOperationsAttendanceRoute =
  AuthenticatedAdminOperationsAttendanceRouteImport.update({
    id: '/admin/operations/attendance',
    path: '/admin/operations/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInternsOnboardingRoute =
  AuthenticatedAdminInternsOnboardingRouteImport.update({
    id: '/admin/interns/onboarding',
    path: '/admin/interns/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInternsActiveRoute =
  AuthenticatedAdminInternsActiveRouteImport.update({
    id: '/admin/interns/active',
    path: '/admin/interns/active',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/feedback-suggestions': typeof AuthenticatedFeedbackSuggestionsRoute
  '/interaction': typeof AuthenticatedInteractionRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/lms-integration': typeof AuthenticatedLmsIntegrationRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pending-work': typeof AuthenticatedPendingWorkRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/project-allocation': typeof AuthenticatedProjectAllocationRoute
  '/questionnaire': typeof AuthenticatedQuestionnaireRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/social': typeof AuthenticatedSocialRoute
  '/support': typeof AuthenticatedSupportRoute
  '/todo': typeof AuthenticatedTodoRoute
  '/admin/activities': typeof AuthenticatedAdminActivitiesRoute
  '/admin/ai-analysis': typeof AuthenticatedAdminAiAnalysisRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/daily-diary': typeof AuthenticatedAdminDailyDiaryRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/leaderboard': typeof AuthenticatedAdminLeaderboardRoute
  '/admin/lms': typeof AuthenticatedAdminLmsRoute
  '/admin/pending-work': typeof AuthenticatedAdminPendingWorkRoute
  '/admin/questionnaires': typeof AuthenticatedAdminQuestionnairesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/todo': typeof AuthenticatedAdminTodoRoute
  '/student/attendance': typeof AuthenticatedStudentAttendanceRoute
  '/super-admin/activities': typeof AuthenticatedSuperAdminActivitiesRoute
  '/super-admin/admin-management': typeof AuthenticatedSuperAdminAdminManagementRoute
  '/super-admin/ai-analysis': typeof AuthenticatedSuperAdminAiAnalysisRoute
  '/super-admin/announcements': typeof AuthenticatedSuperAdminAnnouncementsRoute
  '/super-admin/daily-diary': typeof AuthenticatedSuperAdminDailyDiaryRoute
  '/super-admin/dashboard': typeof AuthenticatedSuperAdminDashboardRoute
  '/super-admin/leaderboard': typeof AuthenticatedSuperAdminLeaderboardRoute
  '/super-admin/lms': typeof AuthenticatedSuperAdminLmsRoute
  '/super-admin/pending-work': typeof AuthenticatedSuperAdminPendingWorkRoute
  '/super-admin/problem-statements': typeof AuthenticatedSuperAdminProblemStatementsRoute
  '/super-admin/questionnaires': typeof AuthenticatedSuperAdminQuestionnairesRoute
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/super-admin/todo': typeof AuthenticatedSuperAdminTodoRoute
  '/u/$id': typeof AuthenticatedUIdRoute
  '/admin/interns/active': typeof AuthenticatedAdminInternsActiveRoute
  '/admin/interns/onboarding': typeof AuthenticatedAdminInternsOnboardingRoute
  '/admin/operations/attendance': typeof AuthenticatedAdminOperationsAttendanceRoute
  '/admin/operations/interactions': typeof AuthenticatedAdminOperationsInteractionsRoute
  '/super-admin/interns/active': typeof AuthenticatedSuperAdminInternsActiveRoute
  '/super-admin/interns/onboarding': typeof AuthenticatedSuperAdminInternsOnboardingRoute
  '/super-admin/operations/attendance': typeof AuthenticatedSuperAdminOperationsAttendanceRoute
  '/super-admin/operations/interactions': typeof AuthenticatedSuperAdminOperationsInteractionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/feedback-suggestions': typeof AuthenticatedFeedbackSuggestionsRoute
  '/interaction': typeof AuthenticatedInteractionRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/lms-integration': typeof AuthenticatedLmsIntegrationRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pending-work': typeof AuthenticatedPendingWorkRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/project-allocation': typeof AuthenticatedProjectAllocationRoute
  '/questionnaire': typeof AuthenticatedQuestionnaireRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/social': typeof AuthenticatedSocialRoute
  '/support': typeof AuthenticatedSupportRoute
  '/todo': typeof AuthenticatedTodoRoute
  '/admin/activities': typeof AuthenticatedAdminActivitiesRoute
  '/admin/ai-analysis': typeof AuthenticatedAdminAiAnalysisRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/daily-diary': typeof AuthenticatedAdminDailyDiaryRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/leaderboard': typeof AuthenticatedAdminLeaderboardRoute
  '/admin/lms': typeof AuthenticatedAdminLmsRoute
  '/admin/pending-work': typeof AuthenticatedAdminPendingWorkRoute
  '/admin/questionnaires': typeof AuthenticatedAdminQuestionnairesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/todo': typeof AuthenticatedAdminTodoRoute
  '/student/attendance': typeof AuthenticatedStudentAttendanceRoute
  '/super-admin/activities': typeof AuthenticatedSuperAdminActivitiesRoute
  '/super-admin/admin-management': typeof AuthenticatedSuperAdminAdminManagementRoute
  '/super-admin/ai-analysis': typeof AuthenticatedSuperAdminAiAnalysisRoute
  '/super-admin/announcements': typeof AuthenticatedSuperAdminAnnouncementsRoute
  '/super-admin/daily-diary': typeof AuthenticatedSuperAdminDailyDiaryRoute
  '/super-admin/dashboard': typeof AuthenticatedSuperAdminDashboardRoute
  '/super-admin/leaderboard': typeof AuthenticatedSuperAdminLeaderboardRoute
  '/super-admin/lms': typeof AuthenticatedSuperAdminLmsRoute
  '/super-admin/pending-work': typeof AuthenticatedSuperAdminPendingWorkRoute
  '/super-admin/problem-statements': typeof AuthenticatedSuperAdminProblemStatementsRoute
  '/super-admin/questionnaires': typeof AuthenticatedSuperAdminQuestionnairesRoute
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/super-admin/todo': typeof AuthenticatedSuperAdminTodoRoute
  '/u/$id': typeof AuthenticatedUIdRoute
  '/admin/interns/active': typeof AuthenticatedAdminInternsActiveRoute
  '/admin/interns/onboarding': typeof AuthenticatedAdminInternsOnboardingRoute
  '/admin/operations/attendance': typeof AuthenticatedAdminOperationsAttendanceRoute
  '/admin/operations/interactions': typeof AuthenticatedAdminOperationsInteractionsRoute
  '/super-admin/interns/active': typeof AuthenticatedSuperAdminInternsActiveRoute
  '/super-admin/interns/onboarding': typeof AuthenticatedSuperAdminInternsOnboardingRoute
  '/super-admin/operations/attendance': typeof AuthenticatedSuperAdminOperationsAttendanceRoute
  '/super-admin/operations/interactions': typeof AuthenticatedSuperAdminOperationsInteractionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diary': typeof AuthenticatedDiaryRoute
  '/_authenticated/feedback-suggestions': typeof AuthenticatedFeedbackSuggestionsRoute
  '/_authenticated/interaction': typeof AuthenticatedInteractionRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/lms-integration': typeof AuthenticatedLmsIntegrationRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pending-work': typeof AuthenticatedPendingWorkRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/project-allocation': typeof AuthenticatedProjectAllocationRoute
  '/_authenticated/questionnaire': typeof AuthenticatedQuestionnaireRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/social': typeof AuthenticatedSocialRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/todo': typeof AuthenticatedTodoRoute
  '/_authenticated/admin/activities': typeof AuthenticatedAdminActivitiesRoute
  '/_authenticated/admin/ai-analysis': typeof AuthenticatedAdminAiAnalysisRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/daily-diary': typeof AuthenticatedAdminDailyDiaryRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/leaderboard': typeof AuthenticatedAdminLeaderboardRoute
  '/_authenticated/admin/lms': typeof AuthenticatedAdminLmsRoute
  '/_authenticated/admin/pending-work': typeof AuthenticatedAdminPendingWorkRoute
  '/_authenticated/admin/questionnaires': typeof AuthenticatedAdminQuestionnairesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/todo': typeof AuthenticatedAdminTodoRoute
  '/_authenticated/student/attendance': typeof AuthenticatedStudentAttendanceRoute
  '/_authenticated/super-admin/activities': typeof AuthenticatedSuperAdminActivitiesRoute
  '/_authenticated/super-admin/admin-management': typeof AuthenticatedSuperAdminAdminManagementRoute
  '/_authenticated/super-admin/ai-analysis': typeof AuthenticatedSuperAdminAiAnalysisRoute
  '/_authenticated/super-admin/announcements': typeof AuthenticatedSuperAdminAnnouncementsRoute
  '/_authenticated/super-admin/daily-diary': typeof AuthenticatedSuperAdminDailyDiaryRoute
  '/_authenticated/super-admin/dashboard': typeof AuthenticatedSuperAdminDashboardRoute
  '/_authenticated/super-admin/leaderboard': typeof AuthenticatedSuperAdminLeaderboardRoute
  '/_authenticated/super-admin/lms': typeof AuthenticatedSuperAdminLmsRoute
  '/_authenticated/super-admin/pending-work': typeof AuthenticatedSuperAdminPendingWorkRoute
  '/_authenticated/super-admin/problem-statements': typeof AuthenticatedSuperAdminProblemStatementsRoute
  '/_authenticated/super-admin/questionnaires': typeof AuthenticatedSuperAdminQuestionnairesRoute
  '/_authenticated/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/_authenticated/super-admin/todo': typeof AuthenticatedSuperAdminTodoRoute
  '/_authenticated/u/$id': typeof AuthenticatedUIdRoute
  '/_authenticated/admin/interns/active': typeof AuthenticatedAdminInternsActiveRoute
  '/_authenticated/admin/interns/onboarding': typeof AuthenticatedAdminInternsOnboardingRoute
  '/_authenticated/admin/operations/attendance': typeof AuthenticatedAdminOperationsAttendanceRoute
  '/_authenticated/admin/operations/interactions': typeof AuthenticatedAdminOperationsInteractionsRoute
  '/_authenticated/super-admin/interns/active': typeof AuthenticatedSuperAdminInternsActiveRoute
  '/_authenticated/super-admin/interns/onboarding': typeof AuthenticatedSuperAdminInternsOnboardingRoute
  '/_authenticated/super-admin/operations/attendance': typeof AuthenticatedSuperAdminOperationsAttendanceRoute
  '/_authenticated/super-admin/operations/interactions': typeof AuthenticatedSuperAdminOperationsInteractionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/unauthorized'
    | '/activities'
    | '/attendance'
    | '/community'
    | '/dashboard'
    | '/diary'
    | '/feedback-suggestions'
    | '/interaction'
    | '/leaderboard'
    | '/lms-integration'
    | '/onboarding'
    | '/pending-work'
    | '/profile'
    | '/project-allocation'
    | '/questionnaire'
    | '/settings'
    | '/social'
    | '/support'
    | '/todo'
    | '/admin/activities'
    | '/admin/ai-analysis'
    | '/admin/announcements'
    | '/admin/daily-diary'
    | '/admin/dashboard'
    | '/admin/leaderboard'
    | '/admin/lms'
    | '/admin/pending-work'
    | '/admin/questionnaires'
    | '/admin/settings'
    | '/admin/todo'
    | '/student/attendance'
    | '/super-admin/activities'
    | '/super-admin/admin-management'
    | '/super-admin/ai-analysis'
    | '/super-admin/announcements'
    | '/super-admin/daily-diary'
    | '/super-admin/dashboard'
    | '/super-admin/leaderboard'
    | '/super-admin/lms'
    | '/super-admin/pending-work'
    | '/super-admin/problem-statements'
    | '/super-admin/questionnaires'
    | '/super-admin/settings'
    | '/super-admin/todo'
    | '/u/$id'
    | '/admin/interns/active'
    | '/admin/interns/onboarding'
    | '/admin/operations/attendance'
    | '/admin/operations/interactions'
    | '/super-admin/interns/active'
    | '/super-admin/interns/onboarding'
    | '/super-admin/operations/attendance'
    | '/super-admin/operations/interactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/unauthorized'
    | '/activities'
    | '/attendance'
    | '/community'
    | '/dashboard'
    | '/diary'
    | '/feedback-suggestions'
    | '/interaction'
    | '/leaderboard'
    | '/lms-integration'
    | '/onboarding'
    | '/pending-work'
    | '/profile'
    | '/project-allocation'
    | '/questionnaire'
    | '/settings'
    | '/social'
    | '/support'
    | '/todo'
    | '/admin/activities'
    | '/admin/ai-analysis'
    | '/admin/announcements'
    | '/admin/daily-diary'
    | '/admin/dashboard'
    | '/admin/leaderboard'
    | '/admin/lms'
    | '/admin/pending-work'
    | '/admin/questionnaires'
    | '/admin/settings'
    | '/admin/todo'
    | '/student/attendance'
    | '/super-admin/activities'
    | '/super-admin/admin-management'
    | '/super-admin/ai-analysis'
    | '/super-admin/announcements'
    | '/super-admin/daily-diary'
    | '/super-admin/dashboard'
    | '/super-admin/leaderboard'
    | '/super-admin/lms'
    | '/super-admin/pending-work'
    | '/super-admin/problem-statements'
    | '/super-admin/questionnaires'
    | '/super-admin/settings'
    | '/super-admin/todo'
    | '/u/$id'
    | '/admin/interns/active'
    | '/admin/interns/onboarding'
    | '/admin/operations/attendance'
    | '/admin/operations/interactions'
    | '/super-admin/interns/active'
    | '/super-admin/interns/onboarding'
    | '/super-admin/operations/attendance'
    | '/super-admin/operations/interactions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/unauthorized'
    | '/_authenticated/activities'
    | '/_authenticated/attendance'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/diary'
    | '/_authenticated/feedback-suggestions'
    | '/_authenticated/interaction'
    | '/_authenticated/leaderboard'
    | '/_authenticated/lms-integration'
    | '/_authenticated/onboarding'
    | '/_authenticated/pending-work'
    | '/_authenticated/profile'
    | '/_authenticated/project-allocation'
    | '/_authenticated/questionnaire'
    | '/_authenticated/settings'
    | '/_authenticated/social'
    | '/_authenticated/support'
    | '/_authenticated/todo'
    | '/_authenticated/admin/activities'
    | '/_authenticated/admin/ai-analysis'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/daily-diary'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/leaderboard'
    | '/_authenticated/admin/lms'
    | '/_authenticated/admin/pending-work'
    | '/_authenticated/admin/questionnaires'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/todo'
    | '/_authenticated/student/attendance'
    | '/_authenticated/super-admin/activities'
    | '/_authenticated/super-admin/admin-management'
    | '/_authenticated/super-admin/ai-analysis'
    | '/_authenticated/super-admin/announcements'
    | '/_authenticated/super-admin/daily-diary'
    | '/_authenticated/super-admin/dashboard'
    | '/_authenticated/super-admin/leaderboard'
    | '/_authenticated/super-admin/lms'
    | '/_authenticated/super-admin/pending-work'
    | '/_authenticated/super-admin/problem-statements'
    | '/_authenticated/super-admin/questionnaires'
    | '/_authenticated/super-admin/settings'
    | '/_authenticated/super-admin/todo'
    | '/_authenticated/u/$id'
    | '/_authenticated/admin/interns/active'
    | '/_authenticated/admin/interns/onboarding'
    | '/_authenticated/admin/operations/attendance'
    | '/_authenticated/admin/operations/interactions'
    | '/_authenticated/super-admin/interns/active'
    | '/_authenticated/super-admin/interns/onboarding'
    | '/_authenticated/super-admin/operations/attendance'
    | '/_authenticated/super-admin/operations/interactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/todo': {
      id: '/_authenticated/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof AuthenticatedTodoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questionnaire': {
      id: '/_authenticated/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof AuthenticatedQuestionnaireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/project-allocation': {
      id: '/_authenticated/project-allocation'
      path: '/project-allocation'
      fullPath: '/project-allocation'
      preLoaderRoute: typeof AuthenticatedProjectAllocationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pending-work': {
      id: '/_authenticated/pending-work'
      path: '/pending-work'
      fullPath: '/pending-work'
      preLoaderRoute: typeof AuthenticatedPendingWorkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lms-integration': {
      id: '/_authenticated/lms-integration'
      path: '/lms-integration'
      fullPath: '/lms-integration'
      preLoaderRoute: typeof AuthenticatedLmsIntegrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interaction': {
      id: '/_authenticated/interaction'
      path: '/interaction'
      fullPath: '/interaction'
      preLoaderRoute: typeof AuthenticatedInteractionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback-suggestions': {
      id: '/_authenticated/feedback-suggestions'
      path: '/feedback-suggestions'
      fullPath: '/feedback-suggestions'
      preLoaderRoute: typeof AuthenticatedFeedbackSuggestionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diary': {
      id: '/_authenticated/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AuthenticatedDiaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$id': {
      id: '/_authenticated/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof AuthenticatedUIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/todo': {
      id: '/_authenticated/super-admin/todo'
      path: '/super-admin/todo'
      fullPath: '/super-admin/todo'
      preLoaderRoute: typeof AuthenticatedSuperAdminTodoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/settings': {
      id: '/_authenticated/super-admin/settings'
      path: '/super-admin/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof AuthenticatedSuperAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/questionnaires': {
      id: '/_authenticated/super-admin/questionnaires'
      path: '/super-admin/questionnaires'
      fullPath: '/super-admin/questionnaires'
      preLoaderRoute: typeof AuthenticatedSuperAdminQuestionnairesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/problem-statements': {
      id: '/_authenticated/super-admin/problem-statements'
      path: '/super-admin/problem-statements'
      fullPath: '/super-admin/problem-statements'
      preLoaderRoute: typeof AuthenticatedSuperAdminProblemStatementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/pending-work': {
      id: '/_authenticated/super-admin/pending-work'
      path: '/super-admin/pending-work'
      fullPath: '/super-admin/pending-work'
      preLoaderRoute: typeof AuthenticatedSuperAdminPendingWorkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/lms': {
      id: '/_authenticated/super-admin/lms'
      path: '/super-admin/lms'
      fullPath: '/super-admin/lms'
      preLoaderRoute: typeof AuthenticatedSuperAdminLmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/leaderboard': {
      id: '/_authenticated/super-admin/leaderboard'
      path: '/super-admin/leaderboard'
      fullPath: '/super-admin/leaderboard'
      preLoaderRoute: typeof AuthenticatedSuperAdminLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/dashboard': {
      id: '/_authenticated/super-admin/dashboard'
      path: '/super-admin/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof AuthenticatedSuperAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/daily-diary': {
      id: '/_authenticated/super-admin/daily-diary'
      path: '/super-admin/daily-diary'
      fullPath: '/super-admin/daily-diary'
      preLoaderRoute: typeof AuthenticatedSuperAdminDailyDiaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/announcements': {
      id: '/_authenticated/super-admin/announcements'
      path: '/super-admin/announcements'
      fullPath: '/super-admin/announcements'
      preLoaderRoute: typeof AuthenticatedSuperAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/ai-analysis': {
      id: '/_authenticated/super-admin/ai-analysis'
      path: '/super-admin/ai-analysis'
      fullPath: '/super-admin/ai-analysis'
      preLoaderRoute: typeof AuthenticatedSuperAdminAiAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/admin-management': {
      id: '/_authenticated/super-admin/admin-management'
      path: '/super-admin/admin-management'
      fullPath: '/super-admin/admin-management'
      preLoaderRoute: typeof AuthenticatedSuperAdminAdminManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/activities': {
      id: '/_authenticated/super-admin/activities'
      path: '/super-admin/activities'
      fullPath: '/super-admin/activities'
      preLoaderRoute: typeof AuthenticatedSuperAdminActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/attendance': {
      id: '/_authenticated/student/attendance'
      path: '/student/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof AuthenticatedStudentAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/todo': {
      id: '/_authenticated/admin/todo'
      path: '/admin/todo'
      fullPath: '/admin/todo'
      preLoaderRoute: typeof AuthenticatedAdminTodoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/questionnaires': {
      id: '/_authenticated/admin/questionnaires'
      path: '/admin/questionnaires'
      fullPath: '/admin/questionnaires'
      preLoaderRoute: typeof AuthenticatedAdminQuestionnairesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pending-work': {
      id: '/_authenticated/admin/pending-work'
      path: '/admin/pending-work'
      fullPath: '/admin/pending-work'
      preLoaderRoute: typeof AuthenticatedAdminPendingWorkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/lms': {
      id: '/_authenticated/admin/lms'
      path: '/admin/lms'
      fullPath: '/admin/lms'
      preLoaderRoute: typeof AuthenticatedAdminLmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/leaderboard': {
      id: '/_authenticated/admin/leaderboard'
      path: '/admin/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AuthenticatedAdminLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/daily-diary': {
      id: '/_authenticated/admin/daily-diary'
      path: '/admin/daily-diary'
      fullPath: '/admin/daily-diary'
      preLoaderRoute: typeof AuthenticatedAdminDailyDiaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ai-analysis': {
      id: '/_authenticated/admin/ai-analysis'
      path: '/admin/ai-analysis'
      fullPath: '/admin/ai-analysis'
      preLoaderRoute: typeof AuthenticatedAdminAiAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/activities': {
      id: '/_authenticated/admin/activities'
      path: '/admin/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AuthenticatedAdminActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/operations/interactions': {
      id: '/_authenticated/super-admin/operations/interactions'
      path: '/super-admin/operations/interactions'
      fullPath: '/super-admin/operations/interactions'
      preLoaderRoute: typeof AuthenticatedSuperAdminOperationsInteractionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/operations/attendance': {
      id: '/_authenticated/super-admin/operations/attendance'
      path: '/super-admin/operations/attendance'
      fullPath: '/super-admin/operations/attendance'
      preLoaderRoute: typeof AuthenticatedSuperAdminOperationsAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/interns/onboarding': {
      id: '/_authenticated/super-admin/interns/onboarding'
      path: '/super-admin/interns/onboarding'
      fullPath: '/super-admin/interns/onboarding'
      preLoaderRoute: typeof AuthenticatedSuperAdminInternsOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/interns/active': {
      id: '/_authenticated/super-admin/interns/active'
      path: '/super-admin/interns/active'
      fullPath: '/super-admin/interns/active'
      preLoaderRoute: typeof AuthenticatedSuperAdminInternsActiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/operations/interactions': {
      id: '/_authenticated/admin/operations/interactions'
      path: '/admin/operations/interactions'
      fullPath: '/admin/operations/interactions'
      preLoaderRoute: typeof AuthenticatedAdminOperationsInteractionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/operations/attendance': {
      id: '/_authenticated/admin/operations/attendance'
      path: '/admin/operations/attendance'
      fullPath: '/admin/operations/attendance'
      preLoaderRoute: typeof AuthenticatedAdminOperationsAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/interns/onboarding': {
      id: '/_authenticated/admin/interns/onboarding'
      path: '/admin/interns/onboarding'
      fullPath: '/admin/interns/onboarding'
      preLoaderRoute: typeof AuthenticatedAdminInternsOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/interns/active': {
      id: '/_authenticated/admin/interns/active'
      path: '/admin/interns/active'
      fullPath: '/admin/interns/active'
      preLoaderRoute: typeof AuthenticatedAdminInternsActiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiaryRoute: typeof AuthenticatedDiaryRoute
  AuthenticatedFeedbackSuggestionsRoute: typeof AuthenticatedFeedbackSuggestionsRoute
  AuthenticatedInteractionRoute: typeof AuthenticatedInteractionRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedLmsIntegrationRoute: typeof AuthenticatedLmsIntegrationRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPendingWorkRoute: typeof AuthenticatedPendingWorkRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProjectAllocationRoute: typeof AuthenticatedProjectAllocationRoute
  AuthenticatedQuestionnaireRoute: typeof AuthenticatedQuestionnaireRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSocialRoute: typeof AuthenticatedSocialRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTodoRoute: typeof AuthenticatedTodoRoute
  AuthenticatedAdminActivitiesRoute: typeof AuthenticatedAdminActivitiesRoute
  AuthenticatedAdminAiAnalysisRoute: typeof AuthenticatedAdminAiAnalysisRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminDailyDiaryRoute: typeof AuthenticatedAdminDailyDiaryRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminLeaderboardRoute: typeof AuthenticatedAdminLeaderboardRoute
  AuthenticatedAdminLmsRoute: typeof AuthenticatedAdminLmsRoute
  AuthenticatedAdminPendingWorkRoute: typeof AuthenticatedAdminPendingWorkRoute
  AuthenticatedAdminQuestionnairesRoute: typeof AuthenticatedAdminQuestionnairesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTodoRoute: typeof AuthenticatedAdminTodoRoute
  AuthenticatedStudentAttendanceRoute: typeof AuthenticatedStudentAttendanceRoute
  AuthenticatedSuperAdminActivitiesRoute: typeof AuthenticatedSuperAdminActivitiesRoute
  AuthenticatedSuperAdminAdminManagementRoute: typeof AuthenticatedSuperAdminAdminManagementRoute
  AuthenticatedSuperAdminAiAnalysisRoute: typeof AuthenticatedSuperAdminAiAnalysisRoute
  AuthenticatedSuperAdminAnnouncementsRoute: typeof AuthenticatedSuperAdminAnnouncementsRoute
  AuthenticatedSuperAdminDailyDiaryRoute: typeof AuthenticatedSuperAdminDailyDiaryRoute
  AuthenticatedSuperAdminDashboardRoute: typeof AuthenticatedSuperAdminDashboardRoute
  AuthenticatedSuperAdminLeaderboardRoute: typeof AuthenticatedSuperAdminLeaderboardRoute
  AuthenticatedSuperAdminLmsRoute: typeof AuthenticatedSuperAdminLmsRoute
  AuthenticatedSuperAdminPendingWorkRoute: typeof AuthenticatedSuperAdminPendingWorkRoute
  AuthenticatedSuperAdminProblemStatementsRoute: typeof AuthenticatedSuperAdminProblemStatementsRoute
  AuthenticatedSuperAdminQuestionnairesRoute: typeof AuthenticatedSuperAdminQuestionnairesRoute
  AuthenticatedSuperAdminSettingsRoute: typeof AuthenticatedSuperAdminSettingsRoute
  AuthenticatedSuperAdminTodoRoute: typeof AuthenticatedSuperAdminTodoRoute
  AuthenticatedUIdRoute: typeof AuthenticatedUIdRoute
  AuthenticatedAdminInternsActiveRoute: typeof AuthenticatedAdminInternsActiveRoute
  AuthenticatedAdminInternsOnboardingRoute: typeof AuthenticatedAdminInternsOnboardingRoute
  AuthenticatedAdminOperationsAttendanceRoute: typeof AuthenticatedAdminOperationsAttendanceRoute
  AuthenticatedAdminOperationsInteractionsRoute: typeof AuthenticatedAdminOperationsInteractionsRoute
  AuthenticatedSuperAdminInternsActiveRoute: typeof AuthenticatedSuperAdminInternsActiveRoute
  AuthenticatedSuperAdminInternsOnboardingRoute: typeof AuthenticatedSuperAdminInternsOnboardingRoute
  AuthenticatedSuperAdminOperationsAttendanceRoute: typeof AuthenticatedSuperAdminOperationsAttendanceRoute
  AuthenticatedSuperAdminOperationsInteractionsRoute: typeof AuthenticatedSuperAdminOperationsInteractionsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiaryRoute: AuthenticatedDiaryRoute,
  AuthenticatedFeedbackSuggestionsRoute: AuthenticatedFeedbackSuggestionsRoute,
  AuthenticatedInteractionRoute: AuthenticatedInteractionRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedLmsIntegrationRoute: AuthenticatedLmsIntegrationRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPendingWorkRoute: AuthenticatedPendingWorkRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProjectAllocationRoute: AuthenticatedProjectAllocationRoute,
  AuthenticatedQuestionnaireRoute: AuthenticatedQuestionnaireRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSocialRoute: AuthenticatedSocialRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTodoRoute: AuthenticatedTodoRoute,
  AuthenticatedAdminActivitiesRoute: AuthenticatedAdminActivitiesRoute,
  AuthenticatedAdminAiAnalysisRoute: AuthenticatedAdminAiAnalysisRoute,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminDailyDiaryRoute: AuthenticatedAdminDailyDiaryRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminLeaderboardRoute: AuthenticatedAdminLeaderboardRoute,
  AuthenticatedAdminLmsRoute: AuthenticatedAdminLmsRoute,
  AuthenticatedAdminPendingWorkRoute: AuthenticatedAdminPendingWorkRoute,
  AuthenticatedAdminQuestionnairesRoute: AuthenticatedAdminQuestionnairesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTodoRoute: AuthenticatedAdminTodoRoute,
  AuthenticatedStudentAttendanceRoute: AuthenticatedStudentAttendanceRoute,
  AuthenticatedSuperAdminActivitiesRoute:
    AuthenticatedSuperAdminActivitiesRoute,
  AuthenticatedSuperAdminAdminManagementRoute:
    AuthenticatedSuperAdminAdminManagementRoute,
  AuthenticatedSuperAdminAiAnalysisRoute:
    AuthenticatedSuperAdminAiAnalysisRoute,
  AuthenticatedSuperAdminAnnouncementsRoute:
    AuthenticatedSuperAdminAnnouncementsRoute,
  AuthenticatedSuperAdminDailyDiaryRoute:
    AuthenticatedSuperAdminDailyDiaryRoute,
  AuthenticatedSuperAdminDashboardRoute: AuthenticatedSuperAdminDashboardRoute,
  AuthenticatedSuperAdminLeaderboardRoute:
    AuthenticatedSuperAdminLeaderboardRoute,
  AuthenticatedSuperAdminLmsRoute: AuthenticatedSuperAdminLmsRoute,
  AuthenticatedSuperAdminPendingWorkRoute:
    AuthenticatedSuperAdminPendingWorkRoute,
  AuthenticatedSuperAdminProblemStatementsRoute:
    AuthenticatedSuperAdminProblemStatementsRoute,
  AuthenticatedSuperAdminQuestionnairesRoute:
    AuthenticatedSuperAdminQuestionnairesRoute,
  AuthenticatedSuperAdminSettingsRoute: AuthenticatedSuperAdminSettingsRoute,
  AuthenticatedSuperAdminTodoRoute: AuthenticatedSuperAdminTodoRoute,
  AuthenticatedUIdRoute: AuthenticatedUIdRoute,
  AuthenticatedAdminInternsActiveRoute: AuthenticatedAdminInternsActiveRoute,
  AuthenticatedAdminInternsOnboardingRoute:
    AuthenticatedAdminInternsOnboardingRoute,
  AuthenticatedAdminOperationsAttendanceRoute:
    AuthenticatedAdminOperationsAttendanceRoute,
  AuthenticatedAdminOperationsInteractionsRoute:
    AuthenticatedAdminOperationsInteractionsRoute,
  AuthenticatedSuperAdminInternsActiveRoute:
    AuthenticatedSuperAdminInternsActiveRoute,
  AuthenticatedSuperAdminInternsOnboardingRoute:
    AuthenticatedSuperAdminInternsOnboardingRoute,
  AuthenticatedSuperAdminOperationsAttendanceRoute:
    AuthenticatedSuperAdminOperationsAttendanceRoute,
  AuthenticatedSuperAdminOperationsInteractionsRoute:
    AuthenticatedSuperAdminOperationsInteractionsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
